### AUTH CONTROLLER TEST
### Get All Users
GET https://localhost:5001/api/auth/allusers
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCIsImN0eSI6IkpXVCJ9.eyJuYW1laWQiOiI1IiwidW5pcXVlX25hbWUiOiJhc2lmIiwibmJmIjoxNjU0MjkxNTA2LCJleHAiOjE2NTQ4OTYzMDYsImlhdCI6MTY1NDI5MTUwNn0.hpbwf-aWWmkwvt5O909He5giaHVpC57F8_yVgJHKEtrVqxWDHF0pAvJ_VPIoWT1jMrvuUKvkLo-Auj0rIfad3Q



### Register new user
POST https://localhost:5001/api/auth/register
Content-Type: application/json

{
    "username": "arif",
    "password": "Pa$$w0rd"
}


### Existing user Login
POST https://localhost:5001/api/auth/login
Content-Type: application/json

{
    "username": "arif",
    "password": "Pa$$w0rd"
}

### Get Individual User
GET https://localhost:5001/api/auth/asif





### POSTS CONTROLLER TEST
### Create Post
POST https://localhost:5001/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCIsImN0eSI6IkpXVCJ9.eyJuYW1laWQiOiI1IiwidW5pcXVlX25hbWUiOiJhc2lmIiwibmJmIjoxNjU0MzUxMTM0LCJleHAiOjE2NTQ5NTU5MzQsImlhdCI6MTY1NDM1MTEzNH0.Vomr7GbVyrfUaL64Dr8iZc3HkQ6b_TWRcrHBCpRkgmbJGjTM2geHIT5NnaZUZhUqZd3uYta-_eyuPex-K013UA

{
    "title": "Asif's third post",
    "content": "Content of Asif's third post"
}

### Update Post
PATCH  https://localhost:5001/api/posts/399
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCIsImN0eSI6IkpXVCJ9.eyJuYW1laWQiOiI1IiwidW5pcXVlX25hbWUiOiJhc2lmIiwibmJmIjoxNjU0MzUzOTAxLCJleHAiOjE2NTQ5NTg3MDEsImlhdCI6MTY1NDM1MzkwMX0.lbWiytpQxtoDHWgCql7fNxDS9qgc1Nuu-owVOFCX5V1Kr0IHbocsb-EE9X1UMquCdq0pCgjpSbSly50koxjhDA

{
    "title": "Asif's third post update",
    "content": "Content of Asif's third post update"
}

### Get All Posts
GET https://localhost:5001/api/posts?pageSize=3&pageNumber=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCIsImN0eSI6IkpXVCJ9.eyJuYW1laWQiOiI1IiwidW5pcXVlX25hbWUiOiJhc2lmIiwibmJmIjoxNjU0MzUxMTM0LCJleHAiOjE2NTQ5NTU5MzQsImlhdCI6MTY1NDM1MTEzNH0.Vomr7GbVyrfUaL64Dr8iZc3HkQ6b_TWRcrHBCpRkgmbJGjTM2geHIT5NnaZUZhUqZd3uYta-_eyuPex-K013UA


### Get Post By Id
GET https://localhost:5001/api/posts/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCIsImN0eSI6IkpXVCJ9.eyJuYW1laWQiOiI1IiwidW5pcXVlX25hbWUiOiJhc2lmIiwibmJmIjoxNjU0MzUxMTM0LCJleHAiOjE2NTQ5NTU5MzQsImlhdCI6MTY1NDM1MTEzNH0.Vomr7GbVyrfUaL64Dr8iZc3HkQ6b_TWRcrHBCpRkgmbJGjTM2geHIT5NnaZUZhUqZd3uYta-_eyuPex-K013UA



### Delete Post By Id
DELETE  https://localhost:5001/api/posts/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCIsImN0eSI6IkpXVCJ9.eyJuYW1laWQiOiI1IiwidW5pcXVlX25hbWUiOiJhc2lmIiwibmJmIjoxNjU0MzUxMTM0LCJleHAiOjE2NTQ5NTU5MzQsImlhdCI6MTY1NDM1MTEzNH0.Vomr7GbVyrfUaL64Dr8iZc3HkQ6b_TWRcrHBCpRkgmbJGjTM2geHIT5NnaZUZhUqZd3uYta-_eyuPex-K013UA