### Get All Users
GET https://localhost:5001/api/auth/allusers
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCIsImN0eSI6IkpXVCJ9.eyJuYW1laWQiOiI1IiwidW5pcXVlX25hbWUiOiJhc2lmIiwibmJmIjoxNjU0MjkxNTA2LCJleHAiOjE2NTQ4OTYzMDYsImlhdCI6MTY1NDI5MTUwNn0.hpbwf-aWWmkwvt5O909He5giaHVpC57F8_yVgJHKEtrVqxWDHF0pAvJ_VPIoWT1jMrvuUKvkLo-Auj0rIfad3Q



### Register new user
POST https://localhost:5001/api/auth/register
Content-Type: application/json

{
    "username": "asif",
    "password": "Pa$$w0rd"
}


### Existing user Login
POST https://localhost:5001/api/auth/login
Content-Type: application/json

{
    "username": "asif",
    "password": "Pa$$w0rd"
}